### ISSUE TITLE
requirements.txt error (Arch linux)

### ISSUE THREAD

**Issue by AvenCores** [PalmaLuv/SteamGiftBot#10]
(env) [avencores@archlinux SteamGiftBot]$ pip install -r requirements.txt 
ERROR: Invalid requirement: 'idna=3.2' (from line 3 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

(env) [avencores@archlinux SteamGiftBot]$ python -V
Python 3.10.9

**Comment by AAnimeshnikk** [comment]
I have same problem, just open the requirements.txt in your text editor and add "=". Must be "idna==3.2".

**Comment by AvenCores** [comment]
(env) [avencores@archlinux SteamGiftBot]$ python main.py 
Traceback (most recent call last):
  File "/home/avencores/Приложения/SteamGiftBot/main.py", line 12, in <module>
    import _logs as _l
  File "/home/avencores/Приложения/SteamGiftBot/_logs.py", line 11, in <module>
    from PyInquirer import ValidationError, Validator, prompt
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/home/avencores/Приложения/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by PalmaLuv** [comment]
For requirements.txt there was a mistake, already corrected 

Regarding the python version, 3.10 is not suitable because some of the libraries that were used in writing the script, supported on 3.9.6 and below
