### ISSUE TITLE
main.py does not start

### ISSUE THREAD

**Issue by AAnimeshnikk** [PalmaLuv/SteamGiftBot#11]
When try to start main.py i see this:
```
Traceback (most recent call last):
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/main.py", line 12, in <module>
    import _logs as _l
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/_logs.py", line 11, in <module>
    from PyInquirer import ValidationError, Validator, prompt
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/env/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

Python version:
```
python -V
Python 3.10.9
```
OS: Arch Linux with i3-wm

**Comment by AvenCores** [comment]
+

![Screenshot_20230222_204613](https://user-images.githubusercontent.com/64781822/220712168-e9512eeb-d8ba-4b12-832c-11e253785114.png)

**Comment by PalmaLuv** [comment]
Regarding the python version, 3.10 is not suitable because some of the libraries that were used in writing the script, supported on 3.9.6 and below

![image](https://user-images.githubusercontent.com/84909252/220728931-21877747-8a25-4b4f-a957-777a972b3799.png)

If you want to use this script on 3.10 you will have to sacrifice the visual

**Comment by Animeshnyk** [comment]
I try to start main.py again, but from python 3.9.6 version and i still get error:
```
(my-virtual-env-3.9.6) [animeshnyk@GodOfLinux SteamGiftBot]$ python main.py
    ______                   ______ _____    ___                      
   / __/ /____ ___ ___ _    / ___(_) _/ /_  / _ \___ ________ ___ ____
  _\ \/ __/ -_) _ `/  ' \  / (_ / / _/ __/ / ___/ _ `/ __(_-</ -_) __/
 /___/\__/\__/\_,_/_/_/_/  \___/_/_/ \__/ /_/   \_,_/_/ /___/\__/_/   

Enjoy using our product!
Created by: github.com/PalmaLuv
Stay tuned for further app updates
Traceback (most recent call last):
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/main.py", line 53, in <module>
    run()
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/main.py", line 26, in run
    cookie = _l.askCookie()
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/_logs.py", line 72, in askCookie
    cookie = ask('input', 'cookie',
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/_logs.py", line 64, in ask
    keyboard.add_hotkey('ctrl+v', lambda: keyboard.write(clipboard.paste()))
  File "/home/animeshnyk/.pyenv/versions/my-virtual-env-3.9.6/lib/python3.9/site-packages/keyboard/__init__.py", line 639, in add_hotkey
    _listener.start_if_necessary()
  File "/home/animeshnyk/.pyenv/versions/my-virtual-env-3.9.6/lib/python3.9/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/home/animeshnyk/.pyenv/versions/my-virtual-env-3.9.6/lib/python3.9/site-packages/keyboard/__init__.py", line 196, in init
    _os_keyboard.init()
  File "/home/animeshnyk/.pyenv/versions/my-virtual-env-3.9.6/lib/python3.9/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/home/animeshnyk/.pyenv/versions/my-virtual-env-3.9.6/lib/python3.9/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/home/animeshnyk/.pyenv/versions/my-virtual-env-3.9.6/lib/python3.9/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
(my-virtual-env-3.9.6) [animeshnyk@GodOfLinux SteamGiftBot]$ python -V
Python 3.9.6
(my-virtual-env-3.9.6) [animeshnyk@GodOfLinux SteamGiftBot]$ sudo python main.py
[sudo] пароль до animeshnyk: 
Traceback (most recent call last):
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/main.py", line 12, in <module>
    import _logs as _l
  File "/home/animeshnyk/SteamGifts/SteamGiftBot/_logs.py", line 10, in <module>
    import six 
ModuleNotFoundError: No module named 'six'
```

**Comment by PalmaLuv** [comment]
I don't know the solution to the problem at the moment, since everything works fine for me and my friends, but I will try to find it soon.

Video from my `Windows 8.1` system [sorry for the quality, that's all I could squeeze out so far].

[Here is the link to the video](https://youtu.be/R2cBlYqVCZg)

In the video, I downloaded the files from GitHub, then uninstalled the libraries that were pre-installed for the script to work properly, then reinstalled them.
